//! BLAKE3-authenticated replica health probes.
//!
//! Generates tamper-evident challenge/response attestations that bind a
//! device identity, membership epoch, and liveness proof into a single
//! `HealthAttestation`. Probes are verified by recomputing the BLAKE3
//! keyed hash and comparing the authentication tag.
//!
//! # Protocol
//!
//! 1. Prober generates a random 32-byte nonce and sends it as a challenge
//!    to the target replica.
//! 2. Target computes `tag = BLAKE3::new_keyed(&shared_secret)
//!    .update(&nonce).update(&device_id).update(&epoch).finalize()`
//!    and returns a `HealthAttestation` carrying the nonce, device_id,
//!    epoch, tag, and a wall-clock timestamp.
//! 3. Prober verifies the attestation by recomputing the tag with the
//!    same inputs and comparing. Epoch staleness is checked by the
//!    `HealthQuorum` aggregator (see `health_quorum.rs`).
//!
//! # Security
//!
//! - The 32-byte shared secret must be distributed out-of-band (e.g.,
//!   membership join token). It is never sent over the wire.
//! - Replay attacks are prevented by the random nonce; a repeated nonce
//!   produces a different tag per-challenge.
//! - Epoch gating ensures attestations from ejected/expired members are
//!   rejected at aggregation time.

use tidefs_membership_epoch::EpochId;

/// 32-byte shared secret for BLAKE3 keyed hashing.
pub type SharedSecret = [u8; 32];

/// 32-byte random nonce for challenge/response liveness.
pub type Nonce = [u8; 32];

/// A device identifier carried in health attestations.
pub type DeviceId = u64;

/// BLAKE3 authentication tag stored as raw bytes for serde compatibility.
pub type AuthTag = [u8; 32];

/// A health attestation binding a device, epoch, and liveness proof
/// with a BLAKE3 authentication tag.
///
/// Generated by the target replica in response to a challenge nonce
/// and verified by the probing side by recomputing the tag.
#[derive(Clone, Debug, Eq, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct HealthAttestation {
    /// The device that produced this attestation.
    pub device_id: DeviceId,
    /// Membership epoch at attestation time.
    pub epoch: EpochId,
    /// Challenge nonce echoed back.
    pub nonce: Nonce,
    /// BLAKE3 authentication tag = keyed_hash(nonce || device_id || epoch).
    pub tag: AuthTag,
    /// Wall-clock timestamp (nanoseconds) when the attestation was produced.
    pub timestamp_ns: u64,
}

impl HealthAttestation {
    /// Recompute the BLAKE3 tag from fields (for verification).
    fn recompute_tag(&self, secret: &SharedSecret) -> AuthTag {
        let mut hasher = blake3::Hasher::new_keyed(secret);
        hasher.update(&self.nonce);
        hasher.update(&self.device_id.to_le_bytes());
        hasher.update(&self.epoch.0.to_le_bytes());
        *hasher.finalize().as_bytes()
    }
}

/// A health-probe generator/verifier holding a shared secret.
///
/// Create one per probing pair (prober + probed) with the same
/// out-of-band shared secret.
#[derive(Clone, Debug)]
pub struct HealthProbe {
    secret: SharedSecret,
}

impl HealthProbe {
    /// Create a new `HealthProbe` with the given 32-byte shared secret.
    pub fn new(secret: SharedSecret) -> Self {
        HealthProbe { secret }
    }

    /// Generate a fresh random 32-byte challenge nonce.
    ///
    /// Uses the OS CSPRNG via `getrandom` for cryptographic-quality
    /// randomness.
    pub fn generate_nonce(&self) -> Nonce {
        let mut nonce = [0u8; 32];
        getrandom::getrandom(&mut nonce).expect("getrandom failed");
        nonce
    }

    /// Produce a `HealthAttestation` for the given device, epoch, and nonce.
    ///
    /// Computes `tag = BLAKE3::new_keyed(&secret)
    ///   .update(&nonce).update(&device_id.to_le_bytes())
    ///   .update(&epoch.0.to_le_bytes()).finalize()`.
    pub fn attest(
        &self,
        device_id: DeviceId,
        epoch: EpochId,
        nonce: &Nonce,
        timestamp_ns: u64,
    ) -> HealthAttestation {
        let mut hasher = blake3::Hasher::new_keyed(&self.secret);
        hasher.update(nonce);
        hasher.update(&device_id.to_le_bytes());
        hasher.update(&epoch.0.to_le_bytes());
        let tag = *hasher.finalize().as_bytes();

        HealthAttestation {
            device_id,
            epoch,
            nonce: *nonce,
            tag,
            timestamp_ns,
        }
    }

    /// Verify a `HealthAttestation` by recomputing the BLAKE3 tag.
    ///
    /// Returns `true` when the tag matches; `false` indicates tampering
    /// or a mismatched shared secret.
    pub fn verify(&self, attestation: &HealthAttestation) -> bool {
        let expected = attestation.recompute_tag(&self.secret);
        expected == attestation.tag
    }

    /// Full round-trip: generate nonce, attest, verify.
    ///
    /// Returns `(nonce, attestation)` if verification passes, or `None`
    /// if the attestation does not verify (should not happen when the
    /// same `HealthProbe` instance is used for both sides; useful as
    /// a self-check).
    pub fn probe_roundtrip(
        &self,
        device_id: DeviceId,
        epoch: EpochId,
        timestamp_ns: u64,
    ) -> Option<(Nonce, HealthAttestation)> {
        let nonce = self.generate_nonce();
        let att = self.attest(device_id, epoch, &nonce, timestamp_ns);
        if self.verify(&att) {
            Some((nonce, att))
        } else {
            None
        }
    }
}

// ── Epoch-gated health sample ──────────────────────────────────────

/// A verified health sample carrying epoch information for
/// staleness gating during quorum aggregation.
///
/// Constructed after `HealthProbe::verify` succeeds; the epoch
/// is compared against the current membership epoch by the
/// `HealthQuorum` aggregator so that attestations from ejected
/// or stale members are rejected.
#[derive(Clone, Debug, Eq, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct HealthSample {
    pub device_id: DeviceId,
    pub epoch: EpochId,
    pub healthy: bool,
    pub timestamp_ns: u64,
    /// Latency of the probe round-trip in nanoseconds, when available.
    pub latency_ns: Option<u64>,
}

impl HealthSample {
    /// Create a health sample from a verified attestation.
    pub fn from_attestation(
        attestation: &HealthAttestation,
        healthy: bool,
        latency_ns: Option<u64>,
    ) -> Self {
        HealthSample {
            device_id: attestation.device_id,
            epoch: attestation.epoch,
            healthy,
            timestamp_ns: attestation.timestamp_ns,
            latency_ns,
        }
    }

    /// Whether this sample is valid with respect to `current_epoch`.
    /// Stale samples (epoch < current) are rejected.
    pub fn is_epoch_valid(&self, current_epoch: EpochId) -> bool {
        self.epoch.0 >= current_epoch.0
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_secret() -> SharedSecret {
        let mut s = [0u8; 32];
        for (i, byte) in s.iter_mut().enumerate() {
            *byte = i as u8;
        }
        s
    }

    fn test_probe() -> HealthProbe {
        HealthProbe::new(test_secret())
    }

    #[test]
    fn attest_and_verify_roundtrip() {
        let probe = test_probe();
        let nonce = probe.generate_nonce();
        let att = probe.attest(1, EpochId::new(5), &nonce, 1000);
        assert!(probe.verify(&att));
    }

    #[test]
    fn tampered_device_id_fails_verification() {
        let probe = test_probe();
        let nonce = probe.generate_nonce();
        let mut att = probe.attest(1, EpochId::new(5), &nonce, 1000);
        att.device_id = 2;
        assert!(!probe.verify(&att));
    }

    #[test]
    fn tampered_epoch_fails_verification() {
        let probe = test_probe();
        let nonce = probe.generate_nonce();
        let mut att = probe.attest(1, EpochId::new(5), &nonce, 1000);
        att.epoch = EpochId::new(6);
        assert!(!probe.verify(&att));
    }

    #[test]
    fn tampered_nonce_fails_verification() {
        let probe = test_probe();
        let nonce = probe.generate_nonce();
        let mut att = probe.attest(1, EpochId::new(5), &nonce, 1000);
        att.nonce[0] ^= 0xFF;
        assert!(!probe.verify(&att));
    }

    #[test]
    fn tampered_tag_fails_verification() {
        let probe = test_probe();
        let nonce = probe.generate_nonce();
        let mut att = probe.attest(1, EpochId::new(5), &nonce, 1000);
        // Flip a byte in the tag
        att.tag[0] ^= 0xFF;
        assert!(!probe.verify(&att));
    }

    #[test]
    fn different_secret_fails_verification() {
        let probe_a = HealthProbe::new(test_secret());
        let mut other_secret = [0u8; 32];
        other_secret[0] = 0xFF;
        let probe_b = HealthProbe::new(other_secret);

        let nonce = probe_a.generate_nonce();
        let att = probe_a.attest(1, EpochId::new(5), &nonce, 1000);
        assert!(probe_a.verify(&att));
        assert!(!probe_b.verify(&att));
    }

    #[test]
    fn probe_roundtrip_succeeds() {
        let probe = test_probe();
        let result = probe.probe_roundtrip(1, EpochId::new(5), 1000);
        assert!(result.is_some());
        let (_nonce, att) = result.unwrap();
        assert_eq!(att.device_id, 1);
        assert_eq!(att.epoch, EpochId::new(5));
        assert_eq!(att.timestamp_ns, 1000);
    }

    #[test]
    fn nonces_are_random() {
        let probe = test_probe();
        let n1 = probe.generate_nonce();
        let n2 = probe.generate_nonce();
        assert_ne!(n1, n2);
    }

    #[test]
    fn health_sample_from_attestation() {
        let probe = test_probe();
        let nonce = probe.generate_nonce();
        let att = probe.attest(42, EpochId::new(3), &nonce, 5000);

        let sample = HealthSample::from_attestation(&att, true, Some(100_000));
        assert_eq!(sample.device_id, 42);
        assert_eq!(sample.epoch, EpochId::new(3));
        assert!(sample.healthy);
        assert_eq!(sample.timestamp_ns, 5000);
        assert_eq!(sample.latency_ns, Some(100_000));
    }

    #[test]
    fn health_sample_unhealthy() {
        let probe = test_probe();
        let nonce = probe.generate_nonce();
        let att = probe.attest(7, EpochId::new(1), &nonce, 3000);

        let sample = HealthSample::from_attestation(&att, false, None);
        assert!(!sample.healthy);
        assert_eq!(sample.latency_ns, None);
    }

    #[test]
    fn epoch_validity_current() {
        let sample = HealthSample {
            device_id: 1,
            epoch: EpochId::new(5),
            healthy: true,
            timestamp_ns: 1000,
            latency_ns: None,
        };
        assert!(sample.is_epoch_valid(EpochId::new(5)));
    }

    #[test]
    fn epoch_validity_newer() {
        let sample = HealthSample {
            device_id: 1,
            epoch: EpochId::new(7),
            healthy: true,
            timestamp_ns: 1000,
            latency_ns: None,
        };
        // Sample from a newer epoch is accepted (epoch has advanced)
        assert!(sample.is_epoch_valid(EpochId::new(5)));
    }

    #[test]
    fn epoch_validity_stale_rejected() {
        let sample = HealthSample {
            device_id: 1,
            epoch: EpochId::new(3),
            healthy: true,
            timestamp_ns: 1000,
            latency_ns: None,
        };
        // Sample from an older epoch is stale
        assert!(!sample.is_epoch_valid(EpochId::new(5)));
    }

    #[test]
    fn epoch_validity_equal() {
        let sample = HealthSample {
            device_id: 1,
            epoch: EpochId::new(10),
            healthy: true,
            timestamp_ns: 1000,
            latency_ns: None,
        };
        assert!(sample.is_epoch_valid(EpochId::new(10)));
    }
}
