use crate::indirect_ping::{
    IndirectPingConfig, IndirectPingRelay, RelayError, RelayRequestHandler, RelayResult,
};
use crate::suspicion_accumulator::{
    SuspicionAccumulator, SuspicionConfig, SuspicionEvent, SuspicionValidation,
};
use crate::types::*;
use ed25519_dalek::{Keypair, PublicKey};
use rand::seq::SliceRandom;
use rand::thread_rng;
use std::collections::BTreeMap;
use tidefs_membership_epoch::{EpochId, HealthClass, MemberClass, MemberId};

/// Outbound indirect-ping relay requests generated by a tick.
#[derive(Default, Debug)]
pub struct IndirectRelayOutbound {
    /// Requests to send: (relay_peer, request).
    pub requests: Vec<(MemberId, SwimIndirectPingRequest)>,
    /// Targets for which no relay peers were available (escalate immediately).
    pub no_relay_targets: Vec<MemberId>,
}

// ---------------------------------------------------------------------------
// Failure detector: SWIM-style direct + indirect ping with suspicion escalation
// ---------------------------------------------------------------------------

/// FailureDetector drives per-peer liveness checks using the SWIM protocol.
///
/// Flow:
/// 1. Send SwimPing to each peer every ping_interval_ms
/// 2. On timeout (ping_timeout_ms), increment failed_ping_count
/// 3. After max_failed_pings_before_suspect consecutive failures, initiate
///    indirect-ping relay via k random peers instead of immediately marking
///    Suspect.
/// 4. If any relay peer confirms reachability, clear suspicion.
/// 5. If all relay peers fail or relay times out, escalate to Suspect.
/// 6. During suspect window (suspicion_window_ms), if no ack clears it,
///    escalate to Dead.
pub struct FailureDetector {
    pub config: MembershipConfig,
    peers: BTreeMap<MemberId, PeerState>,
    #[allow(dead_code)]
    signing_key: Keypair,
    /// Indirect-ping relay manager.
    pub relay: IndirectPingRelay,
    /// Suspicion records emitted by this node
    pub emitted_suspicions: Vec<SuspicionRecord>,
    /// Pending outbound indirect relay requests generated this tick.
    outbound_indirect: IndirectRelayOutbound,
    /// BLAKE3-verified suspicion accumulator for validation-based scoring.
    pub suspicion_accumulator: SuspicionAccumulator,
}

impl FailureDetector {
    pub fn new(config: MembershipConfig, signing_key: Keypair) -> Self {
        let relay_config = IndirectPingConfig {
            relay_peer_count: config.indirect_ping_count,
            relay_timeout_ms: config.ping_timeout_ms * 2,
            max_concurrent_relays: 8,
        };
        Self {
            config,
            peers: BTreeMap::new(),
            signing_key,
            relay: IndirectPingRelay::new(relay_config),
            emitted_suspicions: Vec::new(),
            outbound_indirect: IndirectRelayOutbound::default(),
            suspicion_accumulator: SuspicionAccumulator::new(SuspicionConfig::default()),
        }
    }

    /// Register a peer for heartbeat tracking.
    pub fn register_peer(
        &mut self,
        member_id: MemberId,
        member_class: MemberClass,
        failure_domain: u64,
        epoch: EpochId,
    ) {
        let mut state = PeerState::new(member_id, member_class, failure_domain);
        state.epoch = epoch;
        state.last_ack_millis = now_millis();
        self.peers.insert(member_id, state);
        self.suspicion_accumulator.register_member(member_id);
    }

    /// Remove a peer from tracking.
    pub fn remove_peer(&mut self, member_id: MemberId) {
        self.peers.remove(&member_id);
        self.relay.clear_completed(member_id);
        self.suspicion_accumulator.remove_member(member_id);
    }

    /// Mark a peer as joined (for member-add flow).
    pub fn mark_joining(&mut self, member_id: MemberId) {
        if let Some(peer) = self.peers.get_mut(&member_id) {
            peer.joining = true;
            peer.member_class = MemberClass::Learner;
        }
    }

    /// Promote a peer from learner to voter.
    pub fn promote_to_voter(&mut self, member_id: MemberId) {
        if let Some(peer) = self.peers.get_mut(&member_id) {
            peer.member_class = MemberClass::Voter;
            peer.joining = false;
        }
    }

    /// Begin draining a peer (graceful leave).
    pub fn mark_draining(&mut self, member_id: MemberId) {
        if let Some(peer) = self.peers.get_mut(&member_id) {
            peer.draining = true;
            peer.member_class = MemberClass::DataOnly;
        }
    }

    /// Take outbound indirect-ping relay requests generated by the last tick.
    ///
    /// Returns the requests and resets the internal buffer.  The caller
    /// (transport layer) is responsible for dispatching each request.
    pub fn take_outbound_indirect_requests(&mut self) -> IndirectRelayOutbound {
        std::mem::take(&mut self.outbound_indirect)
    }

    /// Process an inbound indirect-ping request on a relay peer.
    ///
    /// The caller supplies `target_alive` — the result of a direct ping to
    /// the suspect.  Returns an `IndirectPingResponse` to send back to the
    /// requester, or a `RelayError` if the request fails integrity checks.
    pub fn process_indirect_request(
        request: &SwimIndirectPingRequest,
        requester_key: &PublicKey,
        responder_id: MemberId,
        target_alive: bool,
        signing_key: &Keypair,
    ) -> Result<SwimIndirectPingResponse, RelayError> {
        RelayRequestHandler::handle_request(
            request,
            requester_key,
            responder_id,
            target_alive,
            signing_key,
        )
    }

    /// Process an inbound indirect-ping response from a relay peer.
    ///
    /// Returns `Some(RelayResult)` when the relay completes (success or
    /// all-failed), or `None` if still waiting for more responses.
    pub fn process_indirect_response(
        &mut self,
        response: &SwimIndirectPingResponse,
        verifying_key: &PublicKey,
    ) -> Result<Option<RelayResult>, RelayError> {
        let result = self.relay.process_response(response, verifying_key)?;

        if let Some(ref relay_result) = result {
            match relay_result {
                RelayResult::Cleared { target, .. } => {
                    if let Some(peer) = self.peers.get_mut(target) {
                        peer.failed_ping_count = 0;
                        peer.health = HealthClass::Healthy;
                        peer.suspect_since_millis = 0;
                    }
                    self.relay.clear_completed(*target);
                    // Feed success validation to accumulator.
                    self.suspicion_accumulator
                        .record_validation(*target, SuspicionValidation::IndirectPingSuccess);
                }
                RelayResult::AllFailed { target, .. } => {
                    // Feed one IndirectPingFailure lump: all relay peers
                    // reported unreachable.
                    self.suspicion_accumulator.record_validation(
                        *target,
                        SuspicionValidation::IndirectPingFailure {
                            relayed_by: MemberId::ZERO,
                        },
                    );
                    if let Some(peer) = self.peers.get_mut(target) {
                        if peer.health == HealthClass::Healthy {
                            peer.health = HealthClass::Suspect;
                            peer.suspect_since_millis = now_millis();
                            let record = SuspicionRecord::new(
                                *target,
                                MemberId::ZERO,
                                now_millis(),
                                SuspicionSource::IndirectAllTimeout,
                            );
                            self.emitted_suspicions.push(record);
                        }
                    }
                    self.relay.clear_completed(*target);
                }
                RelayResult::Timeout { target, .. } => {
                    // Feed relay timeout as failure validation.
                    self.suspicion_accumulator.record_validation(
                        *target,
                        SuspicionValidation::IndirectPingFailure {
                            relayed_by: MemberId::ZERO,
                        },
                    );
                    if let Some(peer) = self.peers.get_mut(target) {
                        if peer.health == HealthClass::Healthy {
                            peer.health = HealthClass::Suspect;
                            peer.suspect_since_millis = now_millis();
                            let record = SuspicionRecord::new(
                                *target,
                                MemberId::ZERO,
                                now_millis(),
                                SuspicionSource::IndirectAllTimeout,
                            );
                            self.emitted_suspicions.push(record);
                        }
                    }
                    self.relay.clear_completed(*target);
                }
            }
        }

        Ok(result)
    }

    /// Get the list of peers that need a ping this tick.
    /// Returns SwimPing messages to send.
    pub fn tick_pings(
        &mut self,
        local_member_id: MemberId,
        signing_key: &Keypair,
        _verifying_keys: &BTreeMap<MemberId, PublicKey>,
    ) -> Vec<(MemberId, SwimPing)> {
        let now = now_millis();
        let mut pings = Vec::new();
        let all_peers: Vec<MemberId> = self.peers.keys().copied().collect();

        for (member_id, state) in self.peers.iter_mut() {
            if *member_id == local_member_id {
                continue;
            }

            // Don't ping quarantined or draining peers
            if state.health == HealthClass::Down
                || state.member_class == MemberClass::Quarantined
                || state.draining
            {
                continue;
            }

            let time_since_last = now.saturating_sub(state.last_ack_millis);
            if time_since_last >= self.config.ping_interval_ms {
                state.ping_seq_no += 1;

                // Select k random indirect peers
                let indirect_via: Vec<MemberId> = all_peers
                    .iter()
                    .filter(|id| **id != *member_id)
                    .copied()
                    .collect::<Vec<_>>()
                    .choose_multiple(&mut thread_rng(), self.config.indirect_ping_count)
                    .copied()
                    .collect();

                let mut ping = SwimPing {
                    pinger: local_member_id,
                    ping_target: *member_id,
                    seq_no: state.ping_seq_no,
                    pinger_epoch: state.epoch,
                    pinger_epoch_receipt: 0,
                    sent_at_millis: now,
                    indirect_via,
                    signature: Vec::new(),
                };
                ping.sign(signing_key);
                pings.push((*member_id, ping));
            }
        }

        pings
    }

    /// Process an ack received from a peer.
    /// Returns membership deltas to apply and suspicions that have escalated.
    pub fn process_ack(
        &mut self,
        ack: &SwimAck,
        _verifying_keys: &BTreeMap<MemberId, PublicKey>,
    ) -> Result<AckResult, FailureDetectorError> {
        // Verify signature
        let vk = _verifying_keys
            .get(&ack.acker)
            .ok_or(FailureDetectorError::UnknownPeer(ack.acker))?;
        if !ack.verify(vk) {
            return Err(FailureDetectorError::InvalidSignature(ack.acker));
        }

        let now = now_millis();

        // Update peer state
        if let Some(peer) = self.peers.get_mut(&ack.acker) {
            peer.last_ack_millis = now;
            peer.failed_ping_count = 0;

            // If was suspect and now acked, clear suspicion
            if peer.health == HealthClass::Suspect {
                peer.health = HealthClass::Healthy;
                peer.suspect_since_millis = 0;
                // Feed success to accumulator: ack receipt means the peer is reachable.
                self.suspicion_accumulator
                    .record_validation(ack.acker, SuspicionValidation::IndirectPingSuccess);
            }
        }

        // Process suspicion list from ack
        let mut new_suspicions = Vec::new();
        for suspicion in &ack.suspicion_list {
            if let Some(peer) = self.peers.get_mut(&suspicion.subject) {
                // If we get a suspicion from a different node about a peer we think
                // is healthy, we accept the suspicion only after timeout
                if peer.health == HealthClass::Healthy {
                    // Don't immediately mark suspect from piggyback, but escalate
                    // if we also have pending indirect failures
                    if peer.failed_ping_count >= self.config.max_failed_pings_before_suspect {
                        peer.health = HealthClass::Suspect;
                        peer.suspect_since_millis = now;
                        new_suspicions.push(*suspicion);
                    }
                }
            }
        }

        Ok(AckResult {
            acker: ack.acker,
            membership_delta: ack.membership_delta.clone(),
            new_suspicions,
            deltas_applied: 0,
        })
    }

    /// Check for timeouts: peers that haven't acked within ping_timeout_ms.
    /// Returns peers that have newly entered suspect state.
    ///
    /// When a peer crosses the failed-ping threshold, an indirect-ping relay
    /// is initiated instead of immediately marking Suspect.
    /// Relay results flow through `process_indirect_response` and
    /// `tick_relay_timeouts`.
    pub fn tick_timeouts(&mut self) -> Vec<SuspicionRecord> {
        let now = now_millis();
        let mut new_suspicions = Vec::new();

        // Collect member IDs first to avoid borrow conflicts with the relay
        let member_ids: Vec<MemberId> = self.peers.keys().copied().collect();
        for member_id in member_ids {
            let state = match self.peers.get_mut(&member_id) {
                Some(s) => s,
                None => continue,
            };

            if state.health == HealthClass::Down
                || state.member_class == MemberClass::Quarantined
                || state.draining
            {
                continue;
            }

            let time_since_last = now.saturating_sub(state.last_ack_millis);

            if time_since_last >= self.config.ping_timeout_ms {
                state.failed_ping_count += 1;
                // Feed ping-failure validation to the BLAKE3-verified accumulator.
                self.suspicion_accumulator.record_validation(
                    member_id,
                    SuspicionValidation::DirectPingFailure {
                        round: state.ping_seq_no,
                    },
                );

                if state.failed_ping_count >= self.config.max_failed_pings_before_suspect
                    && state.health == HealthClass::Healthy
                {
                    // Initiate indirect-ping relay instead of immediate suspicion
                    let alive_peers: Vec<MemberId> = self
                        .peers
                        .iter()
                        .filter(|(_, s)| s.is_alive())
                        .map(|(id, _)| *id)
                        .collect();

                    // Use a zero-ID placeholder for self; the runtime layer
                    // should supply the real local ID via initiate_relay
                    let local_id = MemberId::ZERO;
                    if let Some(requests) = self.relay.initiate_relay(
                        member_id,
                        local_id,
                        &alive_peers,
                        &self.signing_key,
                    ) {
                        if requests.is_empty() {
                            // No relay peers available — escalate directly
                            // Re-borrow state after relay call
                            if let Some(st) = self.peers.get_mut(&member_id) {
                                st.health = HealthClass::Suspect;
                                st.suspect_since_millis = now;
                            }
                            let record = SuspicionRecord::new(
                                member_id,
                                MemberId::ZERO,
                                now,
                                SuspicionSource::DirectTimeout,
                            );
                            new_suspicions.push(record);
                            self.emitted_suspicions.push(record);
                        } else {
                            self.outbound_indirect.requests.extend(requests);
                        }
                    }
                    // If relay initiation returned None (limit exceeded), we'll
                    // try again on the next tick.
                }
            }

            // Re-borrow state for suspicion window check
            if let Some(st) = self.peers.get_mut(&member_id) {
                if st.health == HealthClass::Suspect
                    && now.saturating_sub(st.suspect_since_millis)
                        >= self.config.suspicion_window_ms
                {
                    st.health = HealthClass::Down;
                }
            }
        }

        new_suspicions
    }

    /// Tick relay timeouts.  Returns suspicion records for targets whose
    /// relays timed out without any success.
    pub fn tick_relay_timeouts(&mut self) -> Vec<SuspicionRecord> {
        let results = self.relay.tick_timeouts();
        let mut suspicions = Vec::new();

        for result in &results {
            if let RelayResult::Timeout { target, .. } = result {
                if let Some(peer) = self.peers.get_mut(target) {
                    if peer.health == HealthClass::Healthy {
                        peer.health = HealthClass::Suspect;
                        peer.suspect_since_millis = now_millis();
                        let record = SuspicionRecord::new(
                            *target,
                            MemberId::ZERO,
                            now_millis(),
                            SuspicionSource::IndirectAllTimeout,
                        );
                        suspicions.push(record);
                        self.emitted_suspicions.push(record);
                    }
                }
                self.relay.clear_completed(*target);
            }
        }

        suspicions
    }

    /// Get voters that are alive.
    pub fn alive_voters(&self) -> Vec<MemberId> {
        self.peers
            .iter()
            .filter(|(_, s)| s.is_alive() && s.is_voter())
            .map(|(id, _)| *id)
            .collect()
    }

    /// Get all alive members.
    pub fn alive_members(&self) -> Vec<MemberId> {
        self.peers
            .iter()
            .filter(|(_, s)| s.is_alive())
            .map(|(id, _)| *id)
            .collect()
    }

    /// Check if quorum is lost (fewer than min_voters_for_quorum alive voters).
    pub fn quorum_lost(&self) -> bool {
        self.alive_voters().len() < self.config.min_voters_for_quorum
    }

    /// Get peer state.
    pub fn get_peer(&self, member_id: MemberId) -> Option<&PeerState> {
        self.peers.get(&member_id)
    }

    /// Get mutable peer state.
    pub fn get_peer_mut(&mut self, member_id: MemberId) -> Option<&mut PeerState> {
        self.peers.get_mut(&member_id)
    }

    /// Get all peer states.
    pub fn all_peers(&self) -> impl Iterator<Item = &PeerState> {
        self.peers.values()
    }

    /// Get the number of tracked peers.
    pub fn peer_count(&self) -> usize {
        self.peers.len()
    }

    /// Check if a peer exists.
    pub fn has_peer(&self, member_id: MemberId) -> bool {
        self.peers.contains_key(&member_id)
    }

    // ------------------------------------------------------------------
    // Suspicion accumulator integration
    // ------------------------------------------------------------------

    /// Advance the suspicion accumulator's internal tick and drain any
    /// state-transition events (MemberSuspected, MemberFailed,
    /// SuspicionCleared).
    ///
    /// Call this once per membership runtime tick.  The returned events
    /// should be converted to `GossipUpdate::SuspicionChange` and
    /// enqueued in the gossip batcher.
    pub fn tick_accumulator(&mut self) -> Vec<SuspicionEvent> {
        self.suspicion_accumulator.tick();
        self.suspicion_accumulator.drain_events()
    }

    /// Drain suspicion events without advancing the tick (e.g., after
    /// processing an ack that may have triggered transitions).
    pub fn drain_suspicion_events(&mut self) -> Vec<SuspicionEvent> {
        self.suspicion_accumulator.drain_events()
    }
}

#[derive(Debug)]
pub struct AckResult {
    pub acker: MemberId,
    pub membership_delta: Vec<MembershipDelta>,
    pub new_suspicions: Vec<SuspicionRecord>,
    pub deltas_applied: usize,
}

#[derive(Debug, thiserror::Error)]
pub enum FailureDetectorError {
    #[error("unknown peer {0:?}")]
    UnknownPeer(MemberId),
    #[error("invalid signature from {0:?}")]
    InvalidSignature(MemberId),
    #[error("membership data digest mismatch from {0:?}")]
    DigestMismatch(MemberId),
}
